# 1. List
The sequence of data elements stored in the list need not to be of the same type.

In [11]:
life=['eat','bath','chore','sleep']

In [15]:
life

['eat', 'bath', 'chore', 'sleep']

In [17]:
type(life)

list

# 2. Tuples
Tuples consist of several elements surrounded by ().

In [20]:
bin_mobilegames=('CODM','PUBGM','MLBB','Minecraft PE','Among Us')
print(f"The second elements of the tuple is {bin_mobilegames[1]}")

The second elements of the tuple is PUBGM


In [19]:
print(f"The elements after thrid element onwards are {bin_mobilegames[2:]}")

The elements after thrid element onwards are ('MLBB', 'Minecraft PE', 'Among Us')


In [18]:
bin_mobilegames=('CODM','PUBGM','MLBB','Minecraft PE','Among Us')
bin_mobilegames[2]

'MLBB'

In [21]:
nested_tuple = (1,2,(100,200,300),6)
print(f"The maximum value of the inner tuple {max(nested_tuple[2])}")

The maximum value of the inner tuple 300


# 3. Dictionary
The Value can be an element of any type, for example, a number or string.

In [22]:
bin_food ={
    "manual_food": "Noodles",
    "approved_food": "Pizza",
    "refused_food": "Poison"
}

In [23]:
print(bin_food)

{'manual_food': 'Noodles', 'approved_food': 'Pizza', 'refused_food': 'Poison'}


In [24]:
bin_food.get('refuse_food')

In [25]:
bin_food['approved_food']

'Pizza'

To update a value associated with a key, use the following code:

In [26]:
bin_food['approved_food']="Meat"
print(bin_food)

{'manual_food': 'Noodles', 'approved_food': 'Meat', 'refused_food': 'Poison'}


# 4. Sets
Set is defined as a collection of elements that can be of different types. The elements are enclosed within { }.

In [27]:
mood = {'sad', 'mad'}
print(mood)

{'sad', 'mad'}


In [30]:
water = {'river','lake', 'ocean','smoke'}
fire = {'air','gas', 'smoke'}

In [31]:
print(f"The union of yellow and red sets is {water|fire}")

The union of yellow and red sets is {'ocean', 'air', 'river', 'smoke', 'lake', 'gas'}


# Data Frames
Two-dimensional structures to store two-dimensional data

In [36]:
import pandas as pd
dataf = pd.DataFrame([
    ['1', 'Roma', 2019],
    ['2', 'Enola Holmes', 2020],
    ['3', 'Black Phanter', 2018]])
dataf.columns = ['id', 'name', 'year']
print(dataf)

  id           name  year
0  1           Roma  2019
1  2   Enola Holmes  2020
2  3  Black Phanter  2018


# Column Selection

In [37]:
dataf[['id', 'name']]

id           name
0  1           Roma
1  2   Enola Holmes
2  3  Black Phanter

In [38]:
dataf.iloc[:,2]

0    2019
1    2020
2    2018
Name: year, dtype: int64

# Row Selection

In [40]:
dataf.iloc[1:2,:]

id          name  year
1  2  Enola Holmes  2020

In [43]:
dataf[dataf.year<2020]

id           name  year
0  1           Roma  2019
2  3  Black Phanter  2018

# Matrix
A matrix is a two-dimensional data structure with a fixed number of columns and rows. Each element of a matrix can be referred to by its column and the row.

In [44]:
import numpy as np

In [45]:
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [46]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [48]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

# Abstract Data Type
Abstraction, in general, is a concept used to define complex systems in terms of their common core functions. The use of this concept to create generic data structures gives birth to Abstract Data Types (ADT). There's 4 kind of ADTs :

# 1. Vector
Using a Python list:

In [49]:
myVector = [22, 33, 44, 55]
print(myVector)

[22, 33, 44, 55]


In [50]:
print(type(myVector))

<class 'list'>


In [51]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [52]:
print(type(myVector))

<class 'numpy.ndarray'>


# 2. Stack
Using the Phyton list :

In [56]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

### Populate the Stack :

In [57]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

#### Pop :

In [58]:
stack.pop()

'Yellow'

In [59]:
stack.isEmpty()

False

In [60]:
colors = ['Red']

In [61]:
colors.append('Green')
colors.append('Yellow')
colors.append('Blue')

In [62]:
colors

['Red', 'Green', 'Yellow', 'Blue']

# Queue
Queue using the elements are added and removed in FIFO format. In the following diagram, the top portion shows the enqueue operation. The bottom portion of the following diagram shows a dequeue operation.

In [63]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [64]:
queue = Queue()
queue.enqueue('1')
queue.enqueue('2')
queue.enqueue('3')
queue.enqueue('4')

In [65]:
print(queue.size())

4


In [66]:
print(queue.dequeue())

1


# Tree
Each tree has a finite set of nodes so that it has a starting data element called a root and a set of nodes joined together by links called branches.

#### There are different types of trees:

Binary tree
Full tree
Perfect tree
Ordered tree